select * from customer limit 20


--1.What is the total revenue generated by male versus female customers .
select gender,sum(purchase_amount) from customer group by gender

--2.Which customers used a discount but still spent more than the average purchase amount.
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--3.Which are the top five products with the highest average review rating.
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

 --4.What is the average purchase amount comparison between standard and express shipping .
select shipping_type,avg(purchase_amount)
from customer
where shipping_type in('Standard','Express')
group by shipping_type
 
--5.Do subscribed customers spend more (average spend and total revenue) compared to non-subscribers .
select subscription_status,avg(purchase_amount),count(customer_id) as total_customer
from customer
group by subscription_status


 --6.Which five products have the highest percentage of purchases with discounts applied .
SELECT item_purchased,
       SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
 
--7.Segment customers into new, returning, and loyal based on their total number of previous purchases .
WITH customer_type AS (
SELECT
customer_id,
previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer
)
SELECT
customer_segment,
COUNT(customer_id) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

--8. What are the top three most purchased products within each category .
WITH item_counts AS (
SELECT
category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--9. Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe .
 SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
--10.What is the total revenue by age group 
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;